//
//  File.swift
//  
//
//  Created by Alexey on 11/15/23.
//

import Foundation

/// Represents an assistant capable of calling the model and utilizing tools.
public struct ASACreateAssistantRequest: Codable, Sendable {
    /// Optional: Assistant's name (max 256 characters).
    public let name: String?

    /// Optional: Description of the assistant (max 512 characters).
    public let description: String?

    /// ID of the model used.
    public let model: String

    /// Optional: System instructions used by the assistant (max 256000 characters).
    public let instructions: String?

    /// Optional: Effort level for model reasoning (low, medium, high). o1 and o3-mini models only
    public let reasoningEffort: String?

    /// Tools available to the assistant (max 128).
    public let tools: [ASAAssistant.Tool]

    /// Optional: Resources utilized by the assistant's tools.
    public let toolResources: ASAAssistant.ToolResources?

    /// Optional: Sampling temperature for output generation (range 0–2, default is 1).
    public let temperature: Double?

    /// Optional: Nucleus sampling parameter (range 0–1, default is 1).
    public let topP: Double?

    /// Optional: Format of the response generated by the model (e.g., auto, text, json_object).
    /// Using this can enforce specific output formats like JSON.
    public let responseFormat: ASAAssistant.ResponseFormat?

    /// Optional: Metadata (up to 16 key-value pairs).
    public let metadata: [String: String]?

    public enum CodingKeys: String, CodingKey {
        case name, description, model, instructions, tools, metadata
        case reasoningEffort = "reasoning_effort"
        case toolResources = "tool_resources"
        case temperature
        case topP = "top_p"
        case responseFormat = "response_format"
    }

    public init(
        name: String? = nil,
        description: String? = nil,
        model: String,
        instructions: String? = nil,
        reasoningEffort: String? = nil,
        tools: [ASAAssistant.Tool] = [],
        toolResources: ASAAssistant.ToolResources? = nil,
        temperature: Double? = nil,
        topP: Double? = nil,
        responseFormat: ASAAssistant.ResponseFormat? = nil,
        metadata: [String : String]? = nil
    ) {
        self.name = name
        self.description = description
        self.model = model
        self.instructions = instructions
        self.reasoningEffort = reasoningEffort
        self.tools = tools
        self.toolResources = toolResources
        self.temperature = temperature
        self.topP = topP
        self.responseFormat = responseFormat
        self.metadata = metadata
    }
}

extension ASACreateAssistantRequest {
    // MARK: - Mock Data

    /// Minimal mock assistant data (only required fields).
    static let assistantMinimal: Self = .init(
        name: nil,
        description: nil,
        model: "gpt-4",
        instructions: nil,
        reasoningEffort: nil,
        tools: [],
        toolResources: nil,
        temperature: nil,
        topP: nil,
        responseFormat: nil,
        metadata: nil
    )

    /// Medium complexity mock assistant data.
    static let assistantMedium: Self = .init(
        name: "Medium Assistant",
        description: "An assistant with moderate complexity",
        model: "gpt-4-turbo",
        instructions: "Answer general queries.",
        reasoningEffort: "medium",
        tools: [
            ASAAssistant.Tool(type: .codeInterpreter, function: nil, fileSearch: nil)
        ],
        toolResources: ASAAssistant.ToolResources(
            codeInterpreter: ASAAssistant.CodeInterpreterResources(fileIds: ["file_123"]),
            fileSearch: nil
        ),
        temperature: 0.7,
        topP: 0.9,
        responseFormat: .auto,
        metadata: ["env": "staging"]
    )

    /// Fully populated mock assistant data (maximum configuration).
    static let assistantFull: Self = .init(
        name: "Full Assistant",
        description: "Fully configured assistant for advanced tasks",
        model: "gpt-4o",
        instructions: "You are a comprehensive assistant handling complex tasks and queries.",
        reasoningEffort: "high",
        tools: [
            ASAAssistant.Tool(
                type: .function,
                function: ASAAssistant.Tool.FunctionTool(
                    name: "calculate",
                    description: "Performs calculations",
                    parameters: ["operation": AnyCodable("add"), "values": AnyCodable([1, 2])],
                    strict: true
                ),
                fileSearch: nil
            ),
            ASAAssistant.Tool(
                type: .fileSearch,
                function: nil,
                fileSearch: ASAAssistant.Tool.FileSearchTool(
                    maxNumResults: 10,
                    rankingOptions: ASAAssistant.Tool.FileSearchTool.RankingOptions(
                        ranker: "auto",
                        scoreThreshold: 0.8
                    )
                )
            )
        ],
        toolResources: ASAAssistant.ToolResources(
            codeInterpreter: ASAAssistant.CodeInterpreterResources(fileIds: ["file_456", "file_789"]),
            fileSearch: ASAAssistant.FileSearchResources(
                vectorStoreIds: ["vector_store_1"],
                vectorStores: [
                    ASAAssistant.FileSearchResources.VectorStore(
                        fileIds: ["file_001", "file_002"],
                        chunkingStrategy: ASAAssistant.FileSearchResources.VectorStore.ChunkingStrategy(
                            type: .static,
                            staticChunking: ASAAssistant.FileSearchResources.VectorStore.ChunkingStrategy.StaticChunking(
                                maxChunkSizeTokens: 1000,
                                chunkOverlapTokens: 500
                            )
                        )
                    )
                ]
            )
        ),
        temperature: 0.5,
        topP: 0.85,
        responseFormat: .jsonObject,
        metadata: ["version": "1.0", "env": "production"]
    )

    /// Collection of all mock assistant configurations.
    static let mocks: [Self] = [
        assistantMinimal,
        assistantMedium,
        assistantFull
    ]
}
