//
//  File.swift
//  
//
//  Created by Alexey on 11/15/23.
//

import Foundation

/// A request structure for modifying an existing assistant.
public struct ASAModifyAssistantRequest: Codable, Sendable {

    /// Optional: ID of the model to use.
    public let model: String?
    
    /// Optional: Effort level for model reasoning (low, medium, high). o1 and o3-mini models only
    public let reasoningEffort: String?

    /// Optional: The name of the assistant. Maximum length is 256 characters.
    public let name: String?

    /// Optional: The description of the assistant. Maximum length is 512 characters.
    public let description: String?

    /// Optional: The system instructions that the assistant uses. Maximum length is 32768 characters.
    public let instructions: String?

    /// Optional: A list of tools enabled on the assistant. Maximum of 128 tools per assistant.
    public let tools: [ASAAssistant.Tool]?

    /// Optional: Resources utilized by the assistant's tools.
    public let toolResources: ASAAssistant.ToolResources?

    /// Optional: A map of key-value pairs for storing additional information. Maximum of 16 pairs.
    public let metadata: [String: String]?

    /// Optional: Sampling temperature for output generation (range 0–2, default is 1).
    public let temperature: Double?

    /// Optional: Nucleus sampling parameter (range 0–1, default is 1).
    public let topP: Double?

    /// Optional: Format of the response generated by the model (e.g., auto, text, json_object).
    /// Using this can enforce specific output formats like JSON.
    public let responseFormat: ASAAssistant.ResponseFormat?

    enum CodingKeys: String, CodingKey {
        case model, name, description, instructions, tools
        case reasoningEffort = "reasoning_effort"
        case toolResources = "tool_resources"
        case temperature
        case topP = "top_p"
        case responseFormat = "response_format"
        case metadata
    }

    public init(
        model: String? = nil,
        reasoningEffort: String? = nil,
        name: String? = nil,
        description: String? = nil,
        instructions: String? = nil,
        tools: [ASAAssistant.Tool]? = nil,
        toolResources: ASAAssistant.ToolResources? = nil,
        metadata: [String : String]? = nil,
        temperature: Double? = nil,
        topP: Double? = nil,
        responseFormat: ASAAssistant.ResponseFormat? = nil
    ) {
        self.model = model
        self.reasoningEffort = reasoningEffort
        self.name = name
        self.description = description
        self.instructions = instructions
        self.tools = tools
        self.toolResources = toolResources
        self.metadata = metadata
        self.temperature = temperature
        self.topP = topP
        self.responseFormat = responseFormat
    }
}
