//
//  File.swift
//  
//
//  Created by Alexey on 11/15/23.
//

import Foundation

/// Represents an assistant capable of calling the model and utilizing tools.
public struct ASAAssistant: Codable, Sendable {
    /// Unique identifier of the assistant (used in API endpoints).
    public let id: String

    /// Object type, always "assistant".
    public let objectType: String

    /// Unix timestamp of assistant creation (in seconds).
    public let createdAt: Int

    /// Optional: Assistant's name (max 256 characters).
    public let name: String?

    /// Optional: Description of the assistant (max 512 characters).
    public let description: String?

    /// ID of the model used.
    public let model: String

    /// Optional: System instructions used by the assistant (max 256000 characters).
    public let instructions: String?

    /// Optional: Effort level for model reasoning (low, medium, high).
    public let reasoningEffort: String?

    /// Tools available to the assistant (max 128).
    public let tools: [Tool]

    /// Optional: Resources utilized by the assistant's tools.
    public let toolResources: ToolResources?

    /// Optional: Sampling temperature for output generation (range 0–2, default is 1).
    public let temperature: Double?

    /// Optional: Nucleus sampling parameter (range 0–1, default is 1).
    public let topP: Double?

    /// Optional: Format of the response generated by the model (e.g., auto, text, json_object).
    /// Using this can enforce specific output formats like JSON.
    public let responseFormat: ResponseFormat?

    /// Optional: Metadata (up to 16 key-value pairs).
    public let metadata: [String: String]?

    public enum CodingKeys: String, CodingKey {
        case id
        case objectType = "object"
        case createdAt = "created_at"
        case name, description, model, instructions, tools, metadata
        case reasoningEffort = "reasoning_effort"
        case toolResources = "tool_resources"
        case temperature
        case topP = "top_p"
        case responseFormat = "response_format"
    }

    // MARK: - Nested Types

    /// Tool available to the assistant.
    public struct Tool: Codable, Sendable {
        /// Type of the tool.
        public let type: ToolType
    }

    /// Supported types of tools.
    public enum ToolType: String, Codable, Sendable {
        case codeInterpreter = "code_interpreter"
        case fileSearch = "file_search"
        case function
    }

    /// Resources used by the assistant's tools.
    public struct ToolResources: Codable, Sendable {
        public let codeInterpreter: CodeInterpreterResources?
        public let fileSearch: FileSearchResources?

        enum CodingKeys: String, CodingKey {
            case codeInterpreter = "code_interpreter"
            case fileSearch = "file_search"
        }
    }

    /// Resources for the code interpreter tool.
    public struct CodeInterpreterResources: Codable, Sendable {
        public let fileIds: [String]

        enum CodingKeys: String, CodingKey {
            case fileIds = "file_ids"
        }
    }

    /// Resources for the file search tool.
    public struct FileSearchResources: Codable, Sendable {
        public let vectorStoreIds: [String]?
        public let vectorStores: [VectorStore]?

        enum CodingKeys: String, CodingKey {
            case vectorStoreIds = "vector_store_ids"
            case vectorStores = "vector_stores"
        }
    }

    /// Vector store for file searches.
    public struct VectorStore: Codable, Sendable {
        public let fileIds: [String]?
        public let chunkingStrategy: ChunkingStrategy?

        enum CodingKeys: String, CodingKey {
            case fileIds = "file_ids"
            case chunkingStrategy = "chunking_strategy"
        }
    }

    /// Strategy for chunking files.
    public struct ChunkingStrategy: Codable, Sendable {
        public let type: String // always "static" when explicitly set
        public let `static`: StaticChunking?
    }

    /// Parameters for static file chunking.
    public struct StaticChunking: Codable, Sendable {
        public let maxChunkSizeTokens: Int
        public let chunkOverlapTokens: Int

        enum CodingKeys: String, CodingKey {
            case maxChunkSizeTokens = "max_chunk_size_tokens"
            case chunkOverlapTokens = "chunk_overlap_tokens"
        }
    }

    /// Specifies the response format from the model. Useful to enforce JSON outputs or plain text.
    public enum ResponseFormat: Codable, Sendable {
        case auto
        case text
        case jsonObject

        public enum CodingKeys: String, CodingKey {
            case type
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "auto": self = .auto
            case "text": self = .text
            case "json_object": self = .jsonObject
            default: self = .auto
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case .auto: try container.encode("auto", forKey: .type)
            case .text: try container.encode("text", forKey: .type)
            case .jsonObject: try container.encode("json_object", forKey: .type)
            }
        }
    }
}

extension ASAAssistant {
    // MARK: - Mock Data

    static let assistantSimple = ASAAssistant(
        id: "simple",
        objectType: "assistant",
        createdAt: 0,
        name: nil,
        description: nil,
        model: "gpt-4",
        instructions: nil,
        reasoningEffort: nil,
        tools: [],
        toolResources: nil,
        temperature: nil,
        topP: nil,
        responseFormat: nil,
        metadata: nil
    )

    static let assistantPartial = ASAAssistant(
        id: "partial",
        objectType: "assistant",
        createdAt: 0,
        name: "Partial Assistant",
        description: nil,
        model: "gpt-4",
        instructions: "Some instructions",
        reasoningEffort: "medium",
        tools: [Tool(
            type: .codeInterpreter
        )],
        toolResources: nil,
        temperature: 0.8,
        topP: nil,
        responseFormat: .text,
        metadata: ["env": "test"]
    )

    static let assistantFull = ASAAssistant(
        id: "full",
        objectType: "assistant",
        createdAt: 0,
        name: "Full Assistant",
        description: "Fully populated assistant",
        model: "gpt-4",
        instructions: "Detailed instructions",
        reasoningEffort: "high",
        tools: [Tool(
            type: .fileSearch
        )],
        toolResources: ToolResources(
            codeInterpreter: nil,
            fileSearch: FileSearchResources(
                vectorStoreIds: ["vs1"],
                vectorStores: nil
            )
        ),
        temperature: 0.5,
        topP: 0.9,
        responseFormat: .jsonObject,
        metadata: ["version": "1.0"]
    )

    static let assistantCustom = ASAAssistant(
        id: "custom",
        objectType: "assistant",
        createdAt: 0,
        name: "Custom Assistant",
        description: "Custom settings assistant",
        model: "gpt-3.5",
        instructions: "Custom instructions",
        reasoningEffort: "low",
        tools: [],
        toolResources: nil,
        temperature: 1.0,
        topP: 0.5,
        responseFormat: .auto,
        metadata: nil
    )

    static let mocks: [ASAAssistant] = [
        assistantSimple,
        assistantPartial,
        assistantFull,
        assistantCustom
    ]
}
