//
//  File.swift
//  
//
//  Created by Alexey on 11/15/23.
//

import Foundation

/// Represents an assistant capable of calling the model and utilizing tools.
public struct ASAAssistant: Codable, Sendable {
    
    /// Unique identifier of the assistant (used in API endpoints).
    public let id: String

    /// Object type, always "assistant".
    public let objectType: String

    /// Unix timestamp of assistant creation (in seconds).
    public let createdAt: Int

    /// Optional: Assistant's name (max 256 characters).
    public let name: String?

    /// Optional: Description of the assistant (max 512 characters).
    public let description: String?

    /// ID of the model used.
    public let model: String

    /// Optional: System instructions used by the assistant (max 256000 characters).
    public let instructions: String?

    /// Tools available to the assistant (max 128).
    public let tools: [Tool]

    /// Optional: Resources utilized by the assistant's tools.
    public let toolResources: ToolResources?

    /// Optional: Sampling temperature for output generation (range 0–2, default is 1).
    public let temperature: Double?

    /// Optional: Nucleus sampling parameter (range 0–1, default is 1).
    public let topP: Double?

    /// Optional: Format of the response generated by the model (e.g., auto, text, json_object).
    /// Using this can enforce specific output formats like JSON.
    public let responseFormat: ResponseFormat?

    /// Optional: Metadata (up to 16 key-value pairs).
    public let metadata: [String: String]?

    enum CodingKeys: String, CodingKey {
        case id, objectType = "object", createdAt = "created_at"
        case name, description, model, instructions, tools, metadata, temperature, topP = "top_p", responseFormat = "response_format", toolResources = "tool_resources"
    }

    public init(
        id: String,
        objectType: String,
        createdAt: Int,
        name: String?,
        description: String?,
        model: String,
        instructions: String?,
        tools: [Tool],
        toolResources: ToolResources?,
        temperature: Double?,
        topP: Double?,
        responseFormat: ResponseFormat?,
        metadata: [String : String]?
    ) {
        self.id = id
        self.objectType = objectType
        self.createdAt = createdAt
        self.name = name
        self.description = description
        self.model = model
        self.instructions = instructions
        self.tools = tools
        self.toolResources = toolResources
        self.temperature = temperature
        self.topP = topP
        self.responseFormat = responseFormat
        self.metadata = metadata
    }

    /// Tool available to the assistant.
    public struct Tool: Codable, Sendable {
        public let type: ToolType
        public let function: FunctionTool?
        public let fileSearch: FileSearchTool?

        enum CodingKeys: String, CodingKey {
            case type, function, fileSearch = "file_search"
        }

        public struct FunctionTool: Codable, Sendable {
            public let name: String
            public let description: String?
            public let parameters: [String: AnyCodable]?
            public let strict: Bool?
        }

        public struct FileSearchTool: Codable, Sendable {
            public let maxNumResults: Int?
            public let rankingOptions: RankingOptions?

            enum CodingKeys: String, CodingKey {
                case maxNumResults = "max_num_results"
                case rankingOptions = "ranking_options"
            }

            public struct RankingOptions: Codable, Sendable {
                public let ranker: String?
                public let scoreThreshold: Double?

                enum CodingKeys: String, CodingKey {
                    case ranker, scoreThreshold = "score_threshold"
                }
            }
        }
    }

    /// Supported types of tools.
    public enum ToolType: String, Codable, Sendable {
        case codeInterpreter = "code_interpreter"
        case fileSearch = "file_search"
        case function
    }

    /// Resources used by the assistant's tools.
    public struct ToolResources: Codable, Sendable {
        public let codeInterpreter: CodeInterpreterResources?
        public let fileSearch: FileSearchResources?

        enum CodingKeys: String, CodingKey {
            case codeInterpreter = "code_interpreter"
            case fileSearch = "file_search"
        }
    }

    /// Resources for the code interpreter tool.
    public struct CodeInterpreterResources: Codable, Sendable {
        public let fileIds: [String]

        enum CodingKeys: String, CodingKey {
            case fileIds = "file_ids"
        }
    }

    /// Resources for the file search tool.
    public struct FileSearchResources: Codable, Sendable {
        public let vectorStoreIds: [String]?
        public let vectorStores: [VectorStore]?

        enum CodingKeys: String, CodingKey {
            case vectorStoreIds = "vector_store_ids"
            case vectorStores = "vector_stores"
        }

        /// Vector store for file searches.
        public struct VectorStore: Codable, Sendable {
            public let fileIds: [String]?
            public let chunkingStrategy: ChunkingStrategy?

            enum CodingKeys: String, CodingKey {
                case fileIds = "file_ids"
                case chunkingStrategy = "chunking_strategy"
            }

            /// Strategy for chunking files.
            public struct ChunkingStrategy: Codable, Sendable {
                public let type: ChunkingType
                public let staticChunking: StaticChunking?

                public enum ChunkingType: String, Codable, Sendable {
                    case auto
                    case `static`
                }

                enum CodingKeys: String, CodingKey {
                    case type
                    case staticChunking = "static"
                }

                /// Parameters for static file chunking.
                public struct StaticChunking: Codable, Sendable {
                    public let maxChunkSizeTokens: Int
                    public let chunkOverlapTokens: Int

                    enum CodingKeys: String, CodingKey {
                        case maxChunkSizeTokens = "max_chunk_size_tokens"
                        case chunkOverlapTokens = "chunk_overlap_tokens"
                    }
                }
            }
        }
    }

    public struct JSONSchema: Codable, Sendable {
        public let name: String
        public let description: String?
        public let schema: [String: AnyCodable]?
        public let strict: Bool?
    }

    public enum ResponseFormat: Codable, Sendable {
        case auto
        case text
        case jsonObject
        case jsonSchema(JSONSchema)

        enum CodingKeys: String, CodingKey {
            case type, jsonSchema = "json_schema"
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "auto": self = .auto
            case "text": self = .text
            case "json_object": self = .jsonObject
            case "json_schema":
                let schema = try container.decode(JSONSchema.self, forKey: .jsonSchema)
                self = .jsonSchema(schema)
            default:
                self = .auto
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case .auto: try container.encode("auto", forKey: .type)
            case .text: try container.encode("text", forKey: .type)
            case .jsonObject: try container.encode("json_object", forKey: .type)
            case .jsonSchema(let schema):
                try container.encode("json_schema", forKey: .type)
                try container.encode(schema, forKey: .jsonSchema)
            }
        }
    }
}

extension ASAAssistant {
    // MARK: - Mock Data

    static let assistantMinimal: Self = .init(
        id: "asst_minimal_001",
        objectType: "assistant",
        createdAt: Int(Date().timeIntervalSince1970),
        name: nil,
        description: nil,
        model: "gpt-4",
        instructions: nil,
        tools: [],
        toolResources: nil,
        temperature: nil,
        topP: nil,
        responseFormat: nil,
        metadata: nil
    )

    /// Средняя конфигурация с основными полями.
    static let assistantMedium: Self = .init(
        id: "asst_medium_001",
        objectType: "assistant",
        createdAt: Int(Date().timeIntervalSince1970),
        name: "Medium Assistant",
        description: "Assistant with moderate complexity",
        model: "gpt-4-turbo",
        instructions: "Answer general queries.",
        tools: [
            Tool(type: .codeInterpreter, function: nil, fileSearch: nil)
        ],
        toolResources: ToolResources(
            codeInterpreter: CodeInterpreterResources(fileIds: ["file_123"]),
            fileSearch: nil
        ),
        temperature: 0.7,
        topP: 0.9,
        responseFormat: .auto,
        metadata: ["env": "staging"]
    )

    /// Полная конфигурация с максимальным набором полей.
    static let assistantFull: Self = .init(
        id: "asst_full_001",
        objectType: "assistant",
        createdAt: Int(Date().timeIntervalSince1970),
        name: "Full Assistant",
        description: "Fully configured assistant for advanced tasks",
        model: "gpt-4o",
        instructions: "You are a comprehensive assistant handling complex tasks and queries.",
        tools: [
            Tool(
                type: .function,
                function: Tool.FunctionTool(
                    name: "calculate",
                    description: "Performs basic arithmetic calculations.",
                    parameters: ["operation": AnyCodable("add"), "values": AnyCodable([1, 2])],
                    strict: true
                ),
                fileSearch: nil
            ),
            Tool(
                type: .fileSearch,
                function: nil,
                fileSearch: Tool.FileSearchTool(
                    maxNumResults: 10,
                    rankingOptions: Tool.FileSearchTool.RankingOptions(
                        ranker: "auto",
                        scoreThreshold: 0.8
                    )
                )
            ),
            Tool(
                type: .codeInterpreter,
                function: nil,
                fileSearch: nil
            )
        ],
        toolResources: ToolResources(
            codeInterpreter: CodeInterpreterResources(
                fileIds: ["file_456", "file_789"]
            ),
            fileSearch: FileSearchResources(
                vectorStoreIds: ["vector_store_1"],
                vectorStores: nil
            )
        ),
        temperature: 0.5,
        topP: 0.85,
        responseFormat: .jsonObject,
        metadata: ["version": "1.0", "env": "production"]
    )

    static let mocks: [Self] = [
        assistantMinimal,
        assistantMedium,
        assistantFull
    ]
}
